### ISSUE TITLE
i got an error, and the lodash is right here, i do not know how to do..

### ISSUE THREAD

**Issue by Naixor** [webdriverio/webdriver.io#26]
```Java
Error: Cannot find module 'lodash._isnative'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/apple/Desktop/node server/fex-webdrivercss/node_modules/webdriverio/node_modules/archiver/node_modules/zip-stream/node_modules/lodash.defaults/node_modules/lodash.keys/index.js:9:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by christian-bromann** [comment]
@Naixor is this an issue related to the webdriver.io website?

**Comment by christian-bromann** [comment]
Closing due to inactivity. Seems that this is related to WebdriverCSS. Please open an issue there.
Thanks!
