### ISSUE TITLE
Unable to run the website

### ISSUE THREAD

**Issue by vvo** [webdriverio/webdriver.io#40]
I followed all the steps in the README but I am getting a weird error.

<details>
```text
> hexo wdio getDocs
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'async' of undefined
    at Hexo.callee$0$0 (/home/vvo/Dev/Algolia/webdriver.io/node_modules/hexo-wdio-generator/build/index.js:34:31)
    at Hexo.tryCatcher (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/method.js:15:34)
    at /home/vvo/Dev/Algolia/webdriver.io/node_modules/hexo/lib/hexo/index.js:192:9
    at Promise._execute (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/promise.js:77:14)
    at Hexo.call (/home/vvo/Dev/Algolia/webdriver.io/node_modules/hexo/lib/hexo/index.js:188:10)
    at /home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/lib/hexo.js:63:17
    at tryCatcher (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
FATAL Cannot read property 'async' of undefined
TypeError: Cannot read property 'async' of undefined
    at Hexo.callee$0$0 (/home/vvo/Dev/Algolia/webdriver.io/node_modules/hexo-wdio-generator/build/index.js:34:31)
    at Hexo.tryCatcher (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/method.js:15:34)
    at /home/vvo/Dev/Algolia/webdriver.io/node_modules/hexo/lib/hexo/index.js:192:9
    at Promise._execute (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/home/vvo/Dev/Algolia/webdriver.io/node_modules/bluebird/js/release/promise.js:77:14)
    at Hexo.call (/home/vvo/Dev/Algolia/webdriver.io/node_modules/hexo/lib/hexo/index.js:188:10)
    at /home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/lib/hexo.js:63:17
    at tryCatcher (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vvo/.nvm/versions/node/v6.2.2/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```
</details>

**Comment by christian-bromann** [comment]
@vvo sorry for the late response. I just updated all necessary components to build the page. It should work without problems now.

**Comment by vvo** [comment]
YES!! Gonna try that very soon, thanks a lot cc @ElPicador
